### ISSUE TITLE
How to use both `APP_ENV=prod` and `APP_ENV=dev` env vars?

### ISSUE THREAD

**Issue by Kocal** [platformsh-templates/symfony4#17]
Hi,

When working on projects, it can be very common to have a branch `master` and a branch `develop`, where:
- branch `master` is for the production with `APP_ENV=prod`
- branch `develop` is for the pre-production, a demo for the client, with `APP_ENV=dev`, allowing us to enable the Symfony Web Profiler, for example

How can we achieve this with this template? Or with Platform.sh itself?

What the `bin/console cache:clear` from the `build` hook will do? Clearing the cache for the default env?
```
hooks:
    build: |
        set -e
        bin/console assets:install --no-debug
        bin/console cache:clear
    deploy: |
        set -e
        bin/console assets:install --symlink --relative public
        bin/console cache:clear
```

How would we be able to run `composer dump-env $APP_ENV`?

Thanks!

**Comment by chadwcarlson** [comment]
Hi @Kocal! Sorry for the very late response. If you're still curious, on Platform.sh there are no differentiating features between how builds are handled on a production environment versus a development environment. That way, builds are environment-independent, and can be reused between environments during branching and merging. 

Now, during the deploy phase, you will have access to [environment variables ](https://docs.platform.sh/development/variables.html#use-platformsh-provided-variables)like `PLATFORM_BRANCH` and `PLATFORM_ENVIRONMENT`. With these, you could have difference deploy hooks across those environments based on their _names_:

```yaml
hooks:
    build: |
        ...
   deploy: |
       if [ "$PLATFORM_BRANCH" = "master" ]; then
          # production deploy steps
      elif ["$PLATFORM_BRANCH" = "develop"]; then
          # development deploy steps
      fi
```

More likely though, you'll want production behavior and then some kind of development/staging behavior for all environments of the same [environment type](https://platform.sh/blog/2021/environment-types-simpler-user-permissions/) where we have three: `production`, `staging`, and `development`

```yaml
hooks:
    build: |
        ...
   deploy: |
       if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then
          # production deploy steps
      elif ["$PLATFORM_ENVIRONMENT_TYPE" = "staging"]; then
          # staging deploy steps
      elif ["$PLATFORM_ENVIRONMENT_TYPE" = "development"]; then
          # dev deploy steps
      fi
```
